version: "3.9"

services:
  nats_uptime_bot:
    build: .
    command:  ./entrypoint.sh
    env_file: ./.envrc
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "9222:9222"
    volumes:
      - "./nats.conf:/etc/nats/nats.conf"
      - nats_jetstream_data:/data/jetstream
    command: ["-c", "/etc/nats/nats.conf"]

  ui:
    build: ./ui/
    env_file: ./ui/.envrc
    volumes:
      - ./ui:/app:rw
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - nats_uptime_bot

  postgres:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: ./.envrc
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nats_uptime_bot" ]
      interval: "10s"
      timeout: "5s"
      retries: 10

volumes:
  nats_jetstream_data: