# Generated by Django 4.2.3 on 2023-09-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="check",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
