# Generated by Django 4.2.3 on 2023-07-17 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="check",
            name="cert_expiry_date",
        ),
        migrations.RemoveField(
            model_name="check",
            name="last_activity",
        ),
        migrations.RemoveField(
            model_name="check",
            name="status",
        ),
        migrations.RemoveField(
            model_name="check",
            name="uptime",
        ),
        migrations.RemoveField(
            model_name="target",
            name="port",
        ),
        migrations.AddField(
            model_name="check",
            name="data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="check",
            name="name",
            field=models.CharField(default=dict, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="target",
            name="domain_name",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("data", models.JSONField(default=dict)),
                (
                    "check_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.check"
                    ),
                ),
            ],
        ),
    ]
