apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-uptime-bot-ui-deployment
  namespace: uptimebot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-uptime-bot-ui
  template:
    metadata:
      labels:
        app: nats-uptime-bot-ui
    spec:
      containers:
        - name: nats-uptime-bot-ui
          image: neox1993/nats_uptime_bot_ui:latest
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nats-uptime-bot-ui-service
  namespace: uptimebot
spec:
  selector:
    app: nats-uptime-bot-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
