FROM node:18.17.0-alpine AS build

WORKDIR /app

COPY package.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build:prod

# Use the official Nginx image for the production build
FROM nginx:alpine


# Copy your custom Nginx configuration
COPY ui-nginx.conf /etc/nginx/conf.d/default.conf

# Copy the built app from the build stage to the Nginx server directory
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80 (default for Nginx)
EXPOSE 3000